/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tugas5.gui;

/**
 *
 * @author ADMIN
 */
public class TugasAtas extends javax.swing.JFrame {

    /**
     * Creates new form TugasAtas
     */
    public TugasAtas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelJudul = new javax.swing.JLabel();
        jRadioButtonASD = new javax.swing.JRadioButton();
        jRadioButtonPemlan = new javax.swing.JRadioButton();
        jRadioButtonmatkomlan = new javax.swing.JRadioButton();
        jRadioButtonProbstat = new javax.swing.JRadioButton();
        jLabelTugas = new javax.swing.JLabel();
        jLabelKuis = new javax.swing.JLabel();
        jLabelUts = new javax.swing.JLabel();
        jLabelUAS = new javax.swing.JLabel();
        jLabelHasil = new javax.swing.JLabel();
        jTextFieldTugas = new javax.swing.JTextField();
        jTextFieldKuis = new javax.swing.JTextField();
        jTextFieldUTS = new javax.swing.JTextField();
        jTextFieldUAS = new javax.swing.JTextField();
        jTextFieldHasil = new javax.swing.JTextField();
        jButtonHitung = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textArea1 = new java.awt.TextArea();
        jButtonNilaiSemuaMatkul = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hitung Nilai Akhir dengan GUI");

        jLabelJudul.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabelJudul.setText("Hitung Nilai Akhir");

        jRadioButtonASD.setText("ASD");
        jRadioButtonASD.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jRadioButtonASD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonASDActionPerformed(evt);
            }
        });

        jRadioButtonPemlan.setText("Pemlan");

        jRadioButtonmatkomlan.setText("Matkomlan");
        jRadioButtonmatkomlan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonmatkomlanActionPerformed(evt);
            }
        });

        jRadioButtonProbstat.setText("Probstat");
        jRadioButtonProbstat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonProbstatActionPerformed(evt);
            }
        });

        jLabelTugas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelTugas.setText("Tugas :");

        jLabelKuis.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelKuis.setText("Kuis :");

        jLabelUts.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelUts.setText("UTS :");

        jLabelUAS.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelUAS.setText("UAS :");

        jLabelHasil.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelHasil.setText("Hasil :");

        jTextFieldTugas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextFieldTugas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTugasActionPerformed(evt);
            }
        });

        jTextFieldKuis.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextFieldKuis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldKuisActionPerformed(evt);
            }
        });

        jTextFieldUTS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextFieldUTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUTSActionPerformed(evt);
            }
        });

        jTextFieldUAS.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextFieldUAS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldUASActionPerformed(evt);
            }
        });

        jTextFieldHasil.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTextFieldHasil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldHasilActionPerformed(evt);
            }
        });

        jButtonHitung.setText("Hitung");
        jButtonHitung.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jScrollPane1.setViewportView(textArea1);

        jButtonNilaiSemuaMatkul.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonNilaiSemuaMatkul.setText("Tampilkan Nilai Semua Matkul");
        jButtonNilaiSemuaMatkul.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButtonNilaiSemuaMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNilaiSemuaMatkulActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jRadioButtonASD, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButtonPemlan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jRadioButtonmatkomlan, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButtonProbstat, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelHasil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabelUAS, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelUts, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelKuis, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabelTugas))
                                        .addGap(32, 32, 32)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jTextFieldTugas, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldKuis, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldUTS, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jTextFieldUAS, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(101, 101, 101)
                        .addComponent(jButtonNilaiSemuaMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(48, 48, 48))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabelJudul))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(170, 170, 170)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(jButtonHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelJudul)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButtonASD)
                            .addComponent(jRadioButtonPemlan)
                            .addComponent(jRadioButtonmatkomlan)
                            .addComponent(jRadioButtonProbstat))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelTugas)
                            .addComponent(jTextFieldTugas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldKuis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelKuis))
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelUts)
                        .addComponent(jTextFieldUTS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldUAS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelUAS))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelHasil))
                .addGap(31, 31, 31)
                .addComponent(jButtonHitung)
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButtonNilaiSemuaMatkul, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButtonASDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonASDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonASDActionPerformed

    private void jRadioButtonmatkomlanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonmatkomlanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonmatkomlanActionPerformed

    private void jRadioButtonProbstatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonProbstatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonProbstatActionPerformed

    private void jButtonNilaiSemuaMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNilaiSemuaMatkulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonNilaiSemuaMatkulActionPerformed

    private void jTextFieldTugasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTugasActionPerformed
        // TODO add your handling code here:
        int tugas = Integer.parseInt(jTextFieldTugas.getText().trim());
    }//GEN-LAST:event_jTextFieldTugasActionPerformed

    private void jTextFieldKuisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldKuisActionPerformed
        // TODO add your handling code here:
        int kuis = Integer.parseInt(jTextFieldKuis.getText().trim());
    }//GEN-LAST:event_jTextFieldKuisActionPerformed

    private void jTextFieldUTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUTSActionPerformed
        // TODO add your handling code here:
        int uts = Integer.parseInt(jTextFieldUTS.getText().trim());
    }//GEN-LAST:event_jTextFieldUTSActionPerformed

    private void jTextFieldUASActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldUASActionPerformed
        // TODO add your handling code here:
        int uas = Integer.parseInt(jTextFieldUAS.getText().trim());
    }//GEN-LAST:event_jTextFieldUASActionPerformed

    private void jTextFieldHasilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldHasilActionPerformed
        // TODO add your handling code here:
//        int hasil = Integer.parseInt(jTextFieldTugas.getText().trim())/4 + 
//                    Integer.parseInt(jTextFieldKuis.getText().trim())/4 +
//                    Integer.parseInt(jTextFieldUTS.getText().trim())/4 +
//                    Integer.parseInt(jTextFieldUAS.getText().trim())/4;
//        
//        String hasilString = String.valueOf(hasil);
//        Object source = e.getItemSelectable();
//        
//        if (source == cbNilaiAngka){
//            jTextFieldHasil.setText(hasilString);
//        } else if (source == cbNilaiHuruf) {
//            jTextFieldHasil.setText("belum ada");
//        }
    }//GEN-LAST:event_jTextFieldHasilActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TugasAtas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TugasAtas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TugasAtas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TugasAtas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TugasAtas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHitung;
    private javax.swing.JButton jButtonNilaiSemuaMatkul;
    private javax.swing.JLabel jLabelHasil;
    private javax.swing.JLabel jLabelJudul;
    private javax.swing.JLabel jLabelKuis;
    private javax.swing.JLabel jLabelTugas;
    private javax.swing.JLabel jLabelUAS;
    private javax.swing.JLabel jLabelUts;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonASD;
    private javax.swing.JRadioButton jRadioButtonPemlan;
    private javax.swing.JRadioButton jRadioButtonProbstat;
    private javax.swing.JRadioButton jRadioButtonmatkomlan;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldHasil;
    private javax.swing.JTextField jTextFieldKuis;
    private javax.swing.JTextField jTextFieldTugas;
    private javax.swing.JTextField jTextFieldUAS;
    private javax.swing.JTextField jTextFieldUTS;
    private java.awt.TextArea textArea1;
    // End of variables declaration//GEN-END:variables
}
